server:
    port: 8880
    context-path: #/liuzh/

logging:
    level:
        tk.mybatis: DEBUG

spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/test
        username: jhipster
        password: jhipster
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

cmbc:
  most:
    mq:
      queueManager: QM_Yan
      host: 9.110.83.36
      port: 1414
      channel: CNN_Yan
      CCSID: 1381
      incomingQueue: LQ01
      outgoingQueue: LQ01
    async:
      corePoolSize: 1
      MaxPoolSize: 10
      QueueCapacity: 1000

#以下属性不可用
#mybatis:
#    pagehelper:
#        dialect: mysql
#        reasonable: true
#        supportMethodsArguments: true
#        returnPageInfo: check
#        params: count=countSql
#    mapper:
#        mappers: MyMapper
#        notEmpty: true
#        style: camelhump
#    sqlSessionFactoryBean:
#        mapperLocations:
#            - classpath:mapper/*.xml
#            - classpath:mapper2/*.xml
#        typeAliasesPackage: tk.mybatis.springboot.model
#    mapperScanner:
#        basePackage: tk.mybatis.springboot.mapper
